version: '3.8'

services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    networks:
      - inception

volumes:
  mariadb_data:

networks:
  inception:
    driver: bridge
